// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHyFLlODZFmzaM_MB0FVoH3ncMNYg_lH8',
    appId: '1:799707036419:web:c539ef864d4d858a50c736',
    messagingSenderId: '799707036419',
    projectId: 'flutter-db45c',
    authDomain: 'flutter-db45c.firebaseapp.com',
    storageBucket: 'flutter-db45c.appspot.com',
    measurementId: 'G-639RXLD4JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmGS8Flgs4mj4zl0vfK3Geg2s96ADqdJI',
    appId: '1:799707036419:android:f66f2d4d343f8d7550c736',
    messagingSenderId: '799707036419',
    projectId: 'flutter-db45c',
    storageBucket: 'flutter-db45c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQgSLxdQSii6fmzMIlSYtknnTXqXaRE1Y',
    appId: '1:799707036419:ios:476fed42fec282a750c736',
    messagingSenderId: '799707036419',
    projectId: 'flutter-db45c',
    storageBucket: 'flutter-db45c.appspot.com',
    iosBundleId: 'com.enye.blocCleanArch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQgSLxdQSii6fmzMIlSYtknnTXqXaRE1Y',
    appId: '1:799707036419:ios:476fed42fec282a750c736',
    messagingSenderId: '799707036419',
    projectId: 'flutter-db45c',
    storageBucket: 'flutter-db45c.appspot.com',
    iosBundleId: 'com.enye.blocCleanArch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHyFLlODZFmzaM_MB0FVoH3ncMNYg_lH8',
    appId: '1:799707036419:web:95cb9efe5ac641f150c736',
    messagingSenderId: '799707036419',
    projectId: 'flutter-db45c',
    authDomain: 'flutter-db45c.firebaseapp.com',
    storageBucket: 'flutter-db45c.appspot.com',
    measurementId: 'G-5RCN97ZRV1',
  );
}
